# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_iplist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='iplist',
            name='service',
        ),
        migrations.RemoveField(
            model_name='iplist',
            name='version',
        ),
        migrations.AlterField(
            model_name='iplist',
            name='port',
            field=models.TextField(),
        ),
    ]
