# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='statue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='domain',
            table='domain',
        ),
    ]
